# Generated by Django 5.0.4 on 2024-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField()),
                ('due_date', models.DateField()),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
