# Generated by Django 5.0.6 on 2024-11-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskade', '0002_remove_task_created_time_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
